deploy:
  before_script:
    - export PATH="/home/ubuntu/.nvm/versions/node/v20.12.2/bin:$PATH"
    - npm install next
    - chmod 400 $SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 34.64.229.17 >> ~/.ssh/known_hosts
    - eval "$(ssh-agent -s)"
    - ssh-add $SSH_KEY
    - export NODE_OPTIONS=--max_old_space_size=800
    - node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'
  script:
    - npm run build
    - mv out html
    - rsync -avz --delete -e "ssh -i $SSH_KEY" html/ elice@34.64.229.17:/home/elice/nginx/html/
  tags:
    - deploy
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

