deploy:
  before_script:
    - export PATH="/home/ubuntu/.nvm/versions/node/v20.14.0/bin:$PATH"
    - npm install next
    - chmod 400 $SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 34.64.229.17 >> ~/.ssh/known_hosts
    - eval "$(ssh-agent -s)"
    - ssh-add $SSH_KEY
    - export NODE_OPTIONS="--max-old-space-size=3500"
    - cat $ENV_LOCAL > .env.local
  script:
    - npm run build
    - mv out html
    - rsync -avz --delete -e "ssh -i $SSH_KEY" html/ elice@34.64.229.17:/home/elice/nginx/html/
  tags:
    - juny
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: manual
      allow_failure: true
