deploy:
  before_script:
    - export PATH="/home/ubuntu/.nvm/versions/node/v20.12.2/bin:$PATH"
    - npm install next
  script:
    - npm run build
    - mv out html
    - rsync -avz --delete html/ elice@34.64.229.17:/home/elice/nginx/html/
  tags:
    - deploy
