import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Provider from "@/layout/Provider";
import { pretendard } from "@/assets/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="bg-indigo-400 font-pretendard" >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
