// import type { Metadata } from "next";
// import { ReactNode } from "react";
// import Provider from "@/layout/Provider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// interface Props {
//   children: ReactNode;
// }

//   return (
//     <html lang="ko" className={pretendard.variable}>
//       <body className="bg-indigo-400 font-pretendard" >
//         <Provider>
//           {children}
//         </Provider>
//       </body>
//     </html>
//   );
// }

import Provider from "@/layout/Provider";
import "./globals.css";
import { pretendard } from "@/assets/font";
import Wrapper from "@/layout/Wrapper";
import React, { ReactNode } from "react";
import PageWrapper from "@/layout/Wrapper/PageWrapper";
import Header from "@/layout/Header";

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="font-pretendard">
        <Provider>
          <Wrapper>
            <Header />
            {children}
          </Wrapper>
        </Provider>
      </body>
    </html>
  );
}
